logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  error:
    include-stacktrace: never
  port: 8080 # server port
  servlet:
    session:
      cookie:
        http-only: true
        max-age: 10800s #3hours
        name: WD_SESSION

spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 262174
    url: jdbc:mysql://1.117.164.81:3306/temp

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "a97081efbb850e759ef1"
            client-secret: "5938dee2c1b27b41c2bd08aed3f11b91285bf572"
          google:
            client_id: "12345"
            client_secret: "1234567"